#include <iostream>

using namespace std;

int main() {

	int x = -1;
	// write try block, throw variabla as exception
	try {

	}
	// implement catch block, print the thrown exception
	catch(){

	}
	cout << "After catch\n";
	return EXIT_SUCCESS;
}

